### ISSUE TITLE
Does not work on 1.20.6

### ISSUE THREAD

**Issue by DeEthria** [refractored/JobListings#2]
Would it be possible to make the plugin 1.20.6 capable of? It does not work on the paper version 1.20.6, it remains red under /plugins.

Log:  https://mclo.gs/aT6KB6o

**Comment by refractored** [comment]
It seems the plugin's MySQL database was not setup correctly, can you verify that it is setup correctly?

**Comment by Leahcimkrob** [comment]
Our config:
we have set user and PW with x

https://mclo.gs/hUXwic3

![image](https://github.com/refractored/JobListings/assets/70509359/ce2737cf-601e-4e62-b821-bf7f96de962a)

**Comment by DeEthria** [comment]
However, we are having problems with the url

  url: "jdbc:mysql://localhost:3306/testminecraft_jobsliting"
  user: "xxxxxxx"
  password: "xxxxxxxxx"

**Comment by refractored** [comment]
Issue should be resolved with the new version

https://github.com/refractored/JobListings/releases
