### ISSUE TITLE
Plugin not finishing booting

### ISSUE THREAD

**Issue by ItzzPotato** [refractored/JobListings#4]
Server version: 1.20.2
Plugin version: v1.1.1

The plugin begins the booting process but simply never finishes it. There is no error or anything; it just stops.
![image_2024-06-10_170431516](https://github.com/refractored/JobListings/assets/72843703/8de9c880-1aef-4919-b785-87e0e69db5fd)
![image_2024-06-10_170454516](https://github.com/refractored/JobListings/assets/72843703/0545d846-90f5-4286-aafa-3f0b78d5dfe7)

**Comment by ItzzPotato** [comment]
Never mind, there is an error
![image_2024-06-10_173804375](https://github.com/refractored/JobListings/assets/72843703/317d7e62-fa00-4a42-8fd6-8f9ebf3261a9)

**Comment by refractored** [comment]
> Never mind, there is an error
> ![image_2024-06-10_173804375](https://github.com/refractored/JobListings/assets/72843703/317d7e62-fa00-4a42-8fd6-8f9ebf3261a9)
> 

May you send your entire latest.log?
